`import Ember from 'ember';`
`import config from './config/environment';`

Router = Ember.Router.extend(location: config.locationType)
Router.map ->

# ---
# generated by js2coffee 2.1.0

`export default Router;`
